refactoring dark theme
swaponline/Design-Componets pull request #112
Opened 2021-09-06 03:36 UTC by Denisfront

2021-09-13 06:19 UTC, tany31 commented on src/assets/icons/swap.svg
> +<svg width="22" height="22" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M15.505 18.495a.7.7 0 00.99 0l4.455-4.455a.7.7 0 10-.99-.99L16 17.01l-3.96-3.96a.7.7 0 10-.99.99l4.455 4.455zM15.3
Может быть сделать `fill=currentColor`? Чтобы не дублировать иконку, а  цвет задавать через css

2021-09-13 06:22 UTC, tany31 commented on src/assets/scss/_theme-variable.scss
> +  --selection-text-color: #{$--black};
Черный цвет выделения для светлой темы будет сливаться с текстом)

2021-09-16 04:35 UTC, alexeyvokin requested changes

2021-09-16 04:35 UTC, alexeyvokin commented on src/constants/theme.js
> +export const SET_APP_THEME = 'setAppTheme'
про `SET_APP_THEME` писал в другом ПРе, просится в отдельный файл констант с типами сообщений

2021-09-16 04:35 UTC, alexeyvokin commented on src/views/Settings/index.vue
> +          setCSSCustomProperty('--main-color', colorForDarkTheme)
Думаю, что добавление префикса `--` к наименованию кастомного свойства стоит вынести в функцию setCSSCustomProperty, т.к. сейчас есть возможность и остальные свойства устанавливать через данную функцию, что противоречит названию (я бы ожидал, что только кастомные могут устанавливаться)

2021-09-16 04:35 UTC, alexeyvokin commented on src/views/Settings/index.vue
> +
getCurrentUserTheme не имеет смысла делать как computed, т.к. функция не зависит от реактивных данных, можно переместить функцию в methods и использовать её внутри handler для selectedTheme

2021-09-16 07:07 UTC, merged