redesign invoice confirm
swaponline/Design-Componets pull request #116
Opened 2021-09-15 06:26 UTC by tany31

2021-09-15 07:09 UTC, Denisfront commented on src/components/Wallets/Modals/ShareModal.vue
> +    data: { type: Object, default: null },
data: { type: Object,  default: () => {} }

2021-09-15 07:09 UTC, Denisfront commented on src/components/Wallets/Modals/ShareModal.vue
> +    title: { type: String, default: 'Share' },
Давай в переменную файла вынесем  `const DEFAULT_TITLE='Share' `

2021-09-16 03:53 UTC, alexeyvokin requested changes

2021-09-16 03:53 UTC, alexeyvokin commented on src/components/Wallets/Modals/ShareModal.vue
> +    data: { type: Object, default: () => {} },
`default: () => {}` -> `default: () => ({})`

2021-09-16 03:53 UTC, alexeyvokin commented on src/components/Wallets/WalletSelector.vue
> +    readOnly: { type: Boolean, default: false }
readOnly можно было назвать подобно html-атрибуту - readonly :)

p.s. это конечно, супер-пупер мелочь

2021-09-16 07:05 UTC, merged