Feature/redesign create profile
swaponline/Design-Componets pull request #117
Opened 2021-09-16 02:34 UTC by Denisfront

2021-09-16 07:50 UTC, tany31 commented on src/components/Profile/SecurityInfoBlock.vue
> +  }
А почему здесь переопределяется стиль кнопки компонента substrate?

2021-09-16 08:09 UTC, tany31 requested changes

2021-09-16 08:09 UTC, tany31 commented on src/layouts/components/MainHeader.vue
> +                :value="!isCreatingOrRecoveringProfile ? notifications.length : null"
Может стоит вынести в компьютед?

2021-09-16 08:09 UTC, tany31 commented on src/views/Profile/Create/SecurityInfo.vue
> +                </div>
Точки разве не должны переключать шаги?

2021-09-16 08:11 UTC, Denisfront commented on src/views/Profile/Create/SecurityInfo.vue
> +                </div>
Нет, это просто декоративные элементы)

2021-09-20 00:02 UTC, Denisfront commented on src/components/Profile/SecurityInfoBlock.vue
> +  }
Она всегда скрыта на мобильных устройствах, а тут нужно показать)

2021-09-21 03:44 UTC, alexeyvokin approved these changes

2021-09-21 03:44 UTC, alexeyvokin commented on src/components/UI/SwapStepper.vue
> +      return Object.keys(this.$slots).length
здесь, может быть стоит сделать $scopedSlots вместо $slots?

2021-09-21 10:58 UTC, merged