add theming service
swaponline/Design-Componets pull request #136
Opened 2021-10-15 11:43 UTC by Denisfront

Automatically update the application theme when the user's system theme changes

2021-10-19 06:00 UTC, tany31 commented on src/App.vue
> +        })
А почему тут решил в функцию не выносить?

2021-10-19 06:00 UTC, tany31 commented on src/services/theme/index.js
> +    return LIGHT_THEME_KEY
А тут есть смысл проверять на светлую, если мы ее по умолчанию возвращаем? Можно оставить проверку только на темную?
```
const isDarkSystemTheme = window.matchMedia(PREFERS_COLOR_SCHEME_DARK).matches

if (isDarkSystemTheme) return DARK_THEME_KEY

return LIGHT_THEME_KEY
```

2021-10-19 06:00 UTC, tany31 commented on src/services/theme/index.js
> +    setStorage(THEME_KEY, appTheme)
А тут не нужно эмитить событие об изменении темы?

2021-10-19 06:00 UTC, tany31 commented on src/App.vue
> +      themeService.setAppTheme(appTheme)
Может быть эту инициализацию стоит в сервис вынести?

2021-10-19 06:00 UTC, tany31 commented on src/App.vue
> +          }
можно так `this.$vuetify.theme.dark = themeService.getIsDark()`

2021-10-22 06:21 UTC, Denisfront commented on src/services/theme/index.js
> +    setStorage(THEME_KEY, appTheme)
Нет. `emmit` нужен только после смены системной темы. Поменял событие `UPDATE_APP_THEME` на `UPDATE_SYSTEM_THEME`, чтобы понятнее было)

2021-10-26 06:06 UTC, alexeyvokin requested changes

2021-10-26 06:06 UTC, alexeyvokin commented on src/services/theme/index.js
> +      window.matchMedia(PREFERS_COLOR_SCHEME_DARK).removeEventListener('change', trackingUserSystemTheme)
это не должно работать, т.к. подписка добавляется к media query list, который возвращается после выполнения matchMedia

2021-10-26 06:06 UTC, alexeyvokin commented on src/services/theme/index.js
> +      window.matchMedia(PREFERS_COLOR_SCHEME_DARK).removeEventListener('change', trackingUserSystemTheme)
вдобавок, каждый раз создается новый объект mql при вызове метода getUserSystemTheme, можно было бы использовать те же инстансы

2021-10-26 06:06 UTC, alexeyvokin commented on src/services/theme/index.js
> +      emitter.emit(events.UPDATE_SYSTEM_THEME, DARK_THEME_KEY)
просится, чтобы событие `UPDATE_SYSTEM_THEME` было в setLightTheme и в setDarkTheme (на самом деле, можно было бы даже объединить эти два метода, т.к. всэ что они делаю - это переключают флаг isDark)

2021-10-26 06:22 UTC, Denisfront commented on src/services/theme/index.js
> +      emitter.emit(events.UPDATE_SYSTEM_THEME, DARK_THEME_KEY)
я же специально назвал событие `UPDATE_SYSTEM_THEME`, чтобы подчеркнуть, что оно нужно только при смене системной темы .`setLightTheme` и `setDarkTheme` это общие методы, которые срабатывают и при ручном переключении темы на странице настроек приложения.

2021-10-27 08:16 UTC, alexeyvokin approved these changes

2021-10-27 08:18 UTC, merged