connection to the library, and initial chart setup
swaponline/Design-Componets pull request #153
Opened 2021-12-20 06:32 UTC by Denisfront

Первая итерация, подключение билеотеки, первичаня настройка графика, создание базового компонента

2021-12-20 07:50 UTC, tany31 requested changes

2021-12-20 07:50 UTC, tany31 commented on src/components/UI/SwapChart.vue
> +        const chartOptions = { ...newOptions, ...oldOptions }
А почему тут сначала newOptions, а потом oldOptions? Если будут одинаковые опции, то old переопределит new?

2021-12-20 07:50 UTC, tany31 commented on src/components/UI/SwapChart.vue
> +        const areaStyleOptions = { ...newStyleOptions, ...oldStyleOptions }
и тут. это работает?

2021-12-20 07:50 UTC, tany31 commented on src/components/Wallets/WalletChart.vue
> +          backgroundColor: this.isDarkTheme ? LAYOUT_BACKGROUND.darkTheme : LAYOUT_BACKGROUND.lightTheme,
Может тут использовать currentTheme? А при инициализации опций использовать прям константы темы. Тогда не нужно будет тернарники писать 
Объявляем:
```
const LAYOUT_BACKGROUND = {
 [DARK_THEME_KEY]: '#0f1422',
 [LIGHT_THEME_KEY]: '#fff'
}
```
Используем:
`LAYOUT_BACKGROUND[this.currentTheme]`

2021-12-20 07:50 UTC, tany31 commented on src/components/Wallets/WalletChart.vue
> +    v-bind="{ datasets }"
Почему здесь через v-bind?

2021-12-20 07:56 UTC, Denisfront commented on src/components/Wallets/WalletChart.vue
> +    v-bind="{ datasets }"
Чтобы не писать ` :datasets="datasets"`

2021-12-20 07:57 UTC, Denisfront commented on src/components/Wallets/WalletChart.vue
> +          backgroundColor: this.isDarkTheme ? LAYOUT_BACKGROUND.darkTheme : LAYOUT_BACKGROUND.lightTheme,
Да, согласен, классное предложение😍

2021-12-20 13:28 UTC, tany31 approved these changes

2021-12-21 07:55 UTC, alexeyvokin requested changes

2021-12-21 07:55 UTC, alexeyvokin commented on src/components/Wallets/WalletChart.vue
> +      return { ...defaultChartOptions, ...this.chartOptions }
сюда просится deep merge

2021-12-21 07:55 UTC, alexeyvokin commented on src/components/Wallets/WalletChart.vue
> +    this.subscriptions.forEach(callback => callback.unsubscribe())
подписки забыл добавить или потом добавятся?

2021-12-21 07:55 UTC, alexeyvokin commented on src/components/UI/SwapChart.vue
> +        const chartOptions = { ...oldOptions, ...newOptions }
нет необходимости старые опции примешивать к новым, какой-то антипаттерн

2021-12-23 09:51 UTC, merged