add profile service tests
swaponline/Design-Componets pull request #166
Opened 2022-01-26 07:53 UTC by tany31

2022-02-16 06:39 UTC, alexeyvokin requested changes

2022-02-16 06:39 UTC, alexeyvokin commented on tests/unit/services/profiles.spec.js
> +    expect(storageService.setStorage).toBeCalledWith(PROFILES_KEY, expect.arrayContaining([addedProfile]))
думаю, здесь лучше заменить на проверку, что `getStorage(PROFILES_KEY)` теперь содержит `addedProfile`, в противном случае, тестируется конкретная реализация, а не результат выполнения функции

2022-02-16 06:39 UTC, alexeyvokin commented on tests/unit/services/profiles.spec.js
> +      expect(storageService.setStorage).toBeCalledWith(CURRENT_PROFILE_ID_KEY, newProfile.id)
аналогично, предлагаю тестировать здесь результат записи в storage, а не вызов метода сервиса

2022-02-16 06:39 UTC, alexeyvokin commented on tests/unit/services/profiles.spec.js
> +      expect(storageService.setStorage).toBeCalledWith(CURRENT_PROFILE_ID_KEY, TEMPORARY_PROFILE_ID)
также аналогично :)

2022-02-16 06:39 UTC, alexeyvokin commented on tests/unit/services/profiles.spec.js
> +    })
есть ощущение, что эту логику можно вынести в отдельный сервис, который будет отвечать чисто за recovering или creating

но это так, мысли в слух...

2022-02-24 04:39 UTC, tany31 commented on tests/unit/services/profiles.spec.js
> +    expect(storageService.setStorage).toBeCalledWith(PROFILES_KEY, expect.arrayContaining([addedProfile]))
т.к. я тут мокаю setStorage и getStorage на свою реализацию, то мне кажется, лучше проверять именно вызов set

2022-02-28 05:53 UTC, alexeyvokin approved these changes

2022-03-11 07:07 UTC, merged