refactoring of the profile creation stages
swaponline/Design-Componets pull request #96
Opened 2021-07-12 09:09 UTC by Denisfront

2021-07-12 09:44 UTC, nikitaGetman requested changes

2021-07-12 09:44 UTC, nikitaGetman commented on src/components/Profile/SecurityInfoBlock.vue
> +  <match-media v-slot="{ desktop }" wrapper-tab="div" class="security-info-block">
wrapper-tag

2021-07-12 09:44 UTC, nikitaGetman commented on src/components/UI/SwapButtonGoBack.vue
> +    </span>
обязательно в span оборачивать?

2021-07-12 09:44 UTC, nikitaGetman commented on src/views/Profile/CreateOrRecover.vue
> +  <match-media v-slot="{ desktop }" wrapper-tab="div">
wrapper-tag

2021-07-12 12:02 UTC, Denisfront commented on src/components/UI/SwapButtonGoBack.vue
> +    </span>
Да, иконка без него не центруется

2021-07-13 12:19 UTC, nikitaGetman approved these changes

2021-07-13 12:19 UTC, merged